version: "3"
services:
    compose-nginx:
        image: nginx:latest
        container_name: "compose-nginx"
        restart: always
        ports:
            - "80:80"
            - "443:443"
        environment:
           - TZ=Asia/Shanghai
        depends_on:
           - "compose-php"
        volumes:
           - "/usr/local/webTool/nginx/conf.d:/etc/nginx/conf.d"
           - "/usr/local/webTool/www:/usr/share/nginx/html"
           - "/usr/local/webTool/nginx/log:/var/log/nginx"
        networks:
           - net-app
    compose-php:
        image: php:7.4-fpm
        container_name: "compose-php"
        restart: always
        ports:
            - "9000:9000"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "/usr/local/webTool/www:/var/www/html/"
        networks:
           - net-app

networks:
    net-app:  
